
language: python

python:
  - "3.5"
  - "3.6"

install:
  - "pip install appdirs flake8"

script:
  - "python setup.py test flake8"

notifications:
  irc:
    channels:
      - "chat.freenode.net#python-sibilant"
    on_success: change
    on_failure: always
    use_notice: true

# The end.
